import React, { useState } from 'react'
import { View, Text, ActivityIndicator } from 'react-native'
import { useStore } from '@/data/store'
import { C, F, S } from '@/theme'
import { Screen, Header, Card, Btn, Row, Chip } from '@/components/ui'
import { WhatChangedStrip } from '@/components/what-changed'
import { AIResultView } from '@/components/ai-result-view'
import { useAI } from '@/hooks/use-ai'
import { studentByUser, detectStudentChanges, overallAvg, attendanceStats, assignmentStats, subjectSeries } from '@/data/stats'
import { Sparkline } from '@/components/charts'

export default function WhatChangedScreen() {
  const { db, user } = useStore()
  const { loading, source, run } = useAI()
  const [result, setResult] = useState<Awaited<ReturnType<typeof run>> | null>(null)
  const [investigated, setInvestigated] = useState(false)

  const student = studentByUser(db, user?.id ?? '')
  if (!student) return null

  const changes = detectStudentChanges(db, student.id)
  const overall = overallAvg(db, student.id)
  const att = attendanceStats(db, student.id)
  const asg = assignmentStats(db, student.id)

  const investigate = async () => {
    setInvestigated(true)
    const r = await run(db, { kind: 'student_investigation', params: { studentId: student.id }, role: 'student' })
    setResult(r)
  }

  return (
    <Screen scroll>
      <Header title="Why did my performance change?" subtitle="AI investigation of your academic data" />
      <WhatChangedStrip
        title="WHAT CHANGED"
        items={changes.slice(0, 4).map((c) => ({
          label: c.subjectName, value: `${c.recent}%`, delta: c.delta,
          color: c.color,
        }))}
      />

      <View style={{ marginTop: S.md }}>
        <Card>
          <Text style={F.h2}>Context checked by this analysis</Text>
          <View style={{ marginTop: S.sm, gap: 8 }}>
            {[
              { label: 'Overall average', value: overall !== null ? `${Math.round(overall)}%` : '—' },
              { label: 'Attendance', value: `${att.pct}%` },
              { label: 'Assignments complete', value: `${asg.completion}%` },
              { label: 'Missing assignments', value: String(asg.missing) },
            ].map((s) => (
              <Row key={s.label} between>
                <Text style={F.body2}>{s.label}</Text>
                <Text style={{ fontWeight: '800' }}>{s.value}</Text>
              </Row>
            ))}
          </View>
          {changes.slice(0, 3).map((c) => (
            <View key={c.subjectId} style={{ marginTop: 10 }}>
              <Row between>
                <Text style={[F.caption, { color: c.color }]}>{c.subjectName} · latest {c.recent}%</Text>
                <Text style={[F.caption, { color: c.delta < 0 ? C.danger : c.delta > 0 ? C.success : C.text3 }]}>{c.delta > 0 ? '+' : ''}{c.delta} pts</Text>
              </Row>
              <Sparkline data={subjectSeries(db, student.id, c.subjectId).map((x) => x.pct)} color={c.color} width={280} height={30} />
            </View>
          ))}
        </Card>
      </View>

      {!investigated ? (
        <Card style={{ marginTop: S.md, backgroundColor: C.aiSoft, borderColor: C.ai + '33' }}>
          <Text style={F.h2}>AI investigation</Text>
          <Text style={[F.body2, { marginTop: 6, lineHeight: 19 }]}>
            The AI combines your marks, attendance and assignments into a structured explanation — WHAT changed, WHERE, HOW significant, relevant patterns and the recommended next action.
          </Text>
          <Btn label={loading ? 'Analysing…' : 'Analyse my performance'} variant="ai" onPress={investigate} loading={loading} style={{ marginTop: S.md }} />
        </Card>
      ) : null}

      {loading ? (
        <Card style={{ marginTop: S.md, alignItems: 'center', paddingVertical: 30 }}>
          <ActivityIndicator size="large" color={C.ai} />
          <Text style={[F.body2, { marginTop: 12 }]}>Examining marks, attendance and assignments…</Text>
        </Card>
      ) : null}

      {result ? (
        <View style={{ marginTop: S.md }}>
          <AIResultView result={result} source={source} sourceNote={source === 'local' ? 'AI service unreachable — built-in analytics engine used.' : 'Generated by Hack Club AI through the secure backend.'} />
        </View>
      ) : null}
    </Screen>
  )
}